version: '2'
services:
  tareaservice-app:
    image: tareaservice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://tareaservice-postgresql:5432/tareaService
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
  tareaservice-postgresql:
    extends:
      file: postgresql.yml
      service: tareaservice-postgresql
